name: Build Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ">=23.7.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Chrome Extension
        run: pnpm build:dist

      - name: Build Chrome Zip
        id: zip_chrome
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: "dist-chrome"
          zipFilePath: "extension-chrome.zip"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: extension-chrome.zip
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
